### Send POST request with json body
POST http://localhost:8080/sendDeveloper
Content-Type: application/json

{
  "developerLevel": "JUNIOR",
  "developerSkillType": "BACK_END",
  "experienceYears": 2,
  "memberId": "mk",
  "name": "mk",
  "age": 20
}

### Send POST request with json body
POST http://localhost:8080/sendDeveloper
Content-Type: application/json

{
  "developerLevel": "JUNIOR",
  "developerSkillType": "FRONT_END",
  "experienceYears": 2,
  "memberId": "ys",
  "name": "ys",
  "age": 20
}

### Send POST request with json body
POST http://localhost:8080/sendDeveloper
Content-Type: application/json

{
  "developerLevel": "JUNIOR",
  "developerSkillType": "BACK_END",
  "experienceYears": 2,
  "memberId": "hw",
  "name": "hw",
  "age": 20
}

### Send POST request with json body
POST http://localhost:8080/sendDeveloper
Content-Type: application/json

{
  "developerLevel": "JUNGNIOR",
  "developerSkillType": "BACK_END",
  "experienceYears": 6,
  "memberId": "zs",
  "name": "zs",
  "age": 20
}
